<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Qu JunJie">
<meta name="dcterms.date" content="2024-09-09">

<title>ISSS626-GAA - Take-Home_Exercise 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01B.html">
 <span class="dropdown-text">Hands-on Exercise 1B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html">
 <span class="dropdown-text">Hands-on Exercise 2A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html">
 <span class="dropdown-text">Hands-on Exercise 2B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A.html">
 <span class="dropdown-text">Hands-on Exercise 5A</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.html">
 <span class="dropdown-text">Hands-on Exercise 5B</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html">
 <span class="dropdown-text">Take-Home Exercise 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html">
 <span class="dropdown-text">Take-Home Exercise 02</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">1. Overview</a></li>
  <li><a href="#get-start" id="toc-get-start" class="nav-link" data-scroll-target="#get-start">2. Get Start</a>
  <ul class="collapse">
  <li><a href="#the-study-area" id="toc-the-study-area" class="nav-link" data-scroll-target="#the-study-area">2.1 The study area</a></li>
  <li><a href="#install-and-launching-r-packages." id="toc-install-and-launching-r-packages." class="nav-link" data-scroll-target="#install-and-launching-r-packages.">2.2 Install and Launching R packages.</a></li>
  </ul></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">3. Data Preparation</a>
  <ul class="collapse">
  <li><a href="#filtering-data-for-bangkok-metropolitan-region-bmr" id="toc-filtering-data-for-bangkok-metropolitan-region-bmr" class="nav-link" data-scroll-target="#filtering-data-for-bangkok-metropolitan-region-bmr">3.1 Filtering Data for Bangkok Metropolitan Region (BMR)</a></li>
  <li><a href="#saving-the-filtered-data" id="toc-saving-the-filtered-data" class="nav-link" data-scroll-target="#saving-the-filtered-data">3.2 Saving the Filtered Data</a></li>
  <li><a href="#loading-the-filtered-data" id="toc-loading-the-filtered-data" class="nav-link" data-scroll-target="#loading-the-filtered-data">3.3 Loading the Filtered Data</a></li>
  <li><a href="#loading-road-network-data" id="toc-loading-road-network-data" class="nav-link" data-scroll-target="#loading-road-network-data">3.4 Loading Road Network Data</a></li>
  <li><a href="#loading-administrative-boundaries-data" id="toc-loading-administrative-boundaries-data" class="nav-link" data-scroll-target="#loading-administrative-boundaries-data">3.5 Loading Administrative Boundaries Data</a></li>
  <li><a href="#filtering-administrative-boundaries-for-bmr-provinces" id="toc-filtering-administrative-boundaries-for-bmr-provinces" class="nav-link" data-scroll-target="#filtering-administrative-boundaries-for-bmr-provinces">3.6 Filtering Administrative Boundaries for BMR Provinces</a></li>
  <li><a href="#setting-coordinate-reference-system-crs" id="toc-setting-coordinate-reference-system-crs" class="nav-link" data-scroll-target="#setting-coordinate-reference-system-crs">3.7Setting Coordinate Reference System (CRS)</a></li>
  <li><a href="#intersecting-road-network-with-administrative-boundaries" id="toc-intersecting-road-network-with-administrative-boundaries" class="nav-link" data-scroll-target="#intersecting-road-network-with-administrative-boundaries">3.8 Intersecting Road Network with Administrative Boundaries</a></li>
  </ul></li>
  <li><a href="#geovisualisation-and-analysis" id="toc-geovisualisation-and-analysis" class="nav-link" data-scroll-target="#geovisualisation-and-analysis">4. Geovisualisation and Analysis</a>
  <ul class="collapse">
  <li><a href="#enhancing-accident-data-with-date-components" id="toc-enhancing-accident-data-with-date-components" class="nav-link" data-scroll-target="#enhancing-accident-data-with-date-components">4.1 Enhancing Accident Data with Date Components</a></li>
  <li><a href="#plotting-the-number-of-accidents-over-time" id="toc-plotting-the-number-of-accidents-over-time" class="nav-link" data-scroll-target="#plotting-the-number-of-accidents-over-time">4.2 Plotting the Number of Accidents Over Time</a>
  <ul class="collapse">
  <li><a href="#observations" id="toc-observations" class="nav-link" data-scroll-target="#observations">Observations:</a></li>
  </ul></li>
  <li><a href="#plotting-the-spatial-distribution-of-accidents-on-the-road-network" id="toc-plotting-the-spatial-distribution-of-accidents-on-the-road-network" class="nav-link" data-scroll-target="#plotting-the-spatial-distribution-of-accidents-on-the-road-network">4.3 Plotting the Spatial Distribution of Accidents on the Road Network</a></li>
  <li><a href="#creating-a-heatmap-of-accidents-by-hour-of-day-and-day-of-the-week" id="toc-creating-a-heatmap-of-accidents-by-hour-of-day-and-day-of-the-week" class="nav-link" data-scroll-target="#creating-a-heatmap-of-accidents-by-hour-of-day-and-day-of-the-week">4.4 Creating a Heatmap of Accidents by Hour of Day and Day of the Week</a>
  <ul class="collapse">
  <li><a href="#observations-1" id="toc-observations-1" class="nav-link" data-scroll-target="#observations-1">Observations:</a></li>
  </ul></li>
  <li><a href="#extracting-the-month-from-the-incident-date" id="toc-extracting-the-month-from-the-incident-date" class="nav-link" data-scroll-target="#extracting-the-month-from-the-incident-date">4.5 Extracting the Month from the Incident Date</a></li>
  <li><a href="#plotting-monthly-accident-counts-over-time" id="toc-plotting-monthly-accident-counts-over-time" class="nav-link" data-scroll-target="#plotting-monthly-accident-counts-over-time">4.6 Plotting Monthly Accident Counts Over Time</a>
  <ul class="collapse">
  <li><a href="#observations-2" id="toc-observations-2" class="nav-link" data-scroll-target="#observations-2">Observations:</a></li>
  </ul></li>
  <li><a href="#seasonal-decomposition-of-monthly-accident-counts" id="toc-seasonal-decomposition-of-monthly-accident-counts" class="nav-link" data-scroll-target="#seasonal-decomposition-of-monthly-accident-counts">4.7 Seasonal Decomposition of Monthly Accident Counts</a>
  <ul class="collapse">
  <li><a href="#observations-3" id="toc-observations-3" class="nav-link" data-scroll-target="#observations-3">Observations:</a></li>
  </ul></li>
  <li><a href="#monthly-spatial-analysis-of-road-accident-hotspots-in-bmr-using-kde" id="toc-monthly-spatial-analysis-of-road-accident-hotspots-in-bmr-using-kde" class="nav-link" data-scroll-target="#monthly-spatial-analysis-of-road-accident-hotspots-in-bmr-using-kde">4.8 Monthly Spatial Analysis of Road Accident Hotspots in BMR Using KDE</a></li>
  <li><a href="#monthly-heatmap-of-road-accident-densities-in-bmr-using-kde" id="toc-monthly-heatmap-of-road-accident-densities-in-bmr-using-kde" class="nav-link" data-scroll-target="#monthly-heatmap-of-road-accident-densities-in-bmr-using-kde">4.9 Monthly Heatmap of Road Accident Densities in BMR Using KDE</a></li>
  <li><a href="#preparing-spatial-accident-data-for-point-pattern-analysis-in-bmr" id="toc-preparing-spatial-accident-data-for-point-pattern-analysis-in-bmr" class="nav-link" data-scroll-target="#preparing-spatial-accident-data-for-point-pattern-analysis-in-bmr">4.10 Preparing Spatial Accident Data for Point Pattern Analysis in BMR</a></li>
  <li><a href="#analyzing-spatial-clustering-of-road-accidents-using-ripleys-k-function" id="toc-analyzing-spatial-clustering-of-road-accidents-using-ripleys-k-function" class="nav-link" data-scroll-target="#analyzing-spatial-clustering-of-road-accidents-using-ripleys-k-function">4.11 Analyzing Spatial Clustering of Road Accidents Using Ripley’s K-function</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation:</a></li>
  </ul></li>
  <li><a href="#monte-carlo-simulation-for-validating-road-accident-clustering-using-ripleys-k-function" id="toc-monte-carlo-simulation-for-validating-road-accident-clustering-using-ripleys-k-function" class="nav-link" data-scroll-target="#monte-carlo-simulation-for-validating-road-accident-clustering-using-ripleys-k-function">4.12 Monte Carlo Simulation for Validating Road Accident Clustering Using Ripley’s K-function</a></li>
  </ul></li>
  <li><a href="#ndke-analysis" id="toc-ndke-analysis" class="nav-link" data-scroll-target="#ndke-analysis">5. NDKE Analysis</a>
  <ul class="collapse">
  <li><a href="#geospatial-analysis-of-bangkok-road-accidents." id="toc-geospatial-analysis-of-bangkok-road-accidents." class="nav-link" data-scroll-target="#geospatial-analysis-of-bangkok-road-accidents.">5.1 Geospatial analysis of Bangkok road accidents.</a></li>
  <li><a href="#crs-transformation-for-spatial-data-in-road-accident-analysis" id="toc-crs-transformation-for-spatial-data-in-road-accident-analysis" class="nav-link" data-scroll-target="#crs-transformation-for-spatial-data-in-road-accident-analysis">5.2 CRS Transformation for Spatial Data in Road Accident Analysis</a></li>
  <li><a href="#preprocessing-road-network-data-filtering-and-geometry-casting-in-geospatial-analysis" id="toc-preprocessing-road-network-data-filtering-and-geometry-casting-in-geospatial-analysis" class="nav-link" data-scroll-target="#preprocessing-road-network-data-filtering-and-geometry-casting-in-geospatial-analysis">5.3 Preprocessing Road Network Data: Filtering and Geometry Casting in Geospatial Analysis</a></li>
  <li><a href="#dividing-and-sampling-road-networks-lixelization-and-center-extraction-for-spatial-analysis" id="toc-dividing-and-sampling-road-networks-lixelization-and-center-extraction-for-spatial-analysis" class="nav-link" data-scroll-target="#dividing-and-sampling-road-networks-lixelization-and-center-extraction-for-spatial-analysis">5.4 Dividing and Sampling Road Networks: Lixelization and Center Extraction for Spatial Analysis</a></li>
  <li><a href="#network-kernel-density-estimation-nkde-for-road-accident-analysis-with-parallel-processing" id="toc-network-kernel-density-estimation-nkde-for-road-accident-analysis-with-parallel-processing" class="nav-link" data-scroll-target="#network-kernel-density-estimation-nkde-for-road-accident-analysis-with-parallel-processing">5.5 Network Kernel Density Estimation (NKDE) for Road Accident Analysis with Parallel Processing</a>
  <ul class="collapse">
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion:</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home_Exercise 1</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Qu JunJie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 9, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 23, 2024</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>1. Overview</h1>
<p>Road traffic accidents are a global health concern, responsible for approximately 1.19 million deaths annually and leaving 20–50 million people injured. Vulnerable road users—pedestrians, cyclists, and motorcyclists—are disproportionately affected. In Thailand, recognized as having the deadliest roads in Southeast Asia, about 20,000 people die annually in traffic accidents, with accidents peaking on national highways and accident-prone zones termed “black spots.”</p>
</section>
<section id="get-start" class="level1">
<h1>2. Get Start</h1>
<p>The specific objectives of this take-home exercise are as follows:</p>
<ul>
<li><p>To visualize the spatio-temporal dynamics of road traffic accidents in BMR using appropriate statistical graphics and geovisualization methods.</p></li>
<li><p>To conduct detailed spatial analysis of road traffic accidents using appropriate Network Spatial Point Patterns Analysis methods.</p></li>
<li><p>To conduct detailed spatio-temporal analysis of road traffic accidents using appropriate Temporal Network Spatial Point Patterns Analysis methods.</p></li>
</ul>
<section id="the-study-area" class="level2">
<h2 class="anchored" data-anchor-id="the-study-area">2.1 The study area</h2>
<p>The focus of this study would be in Bangkok Metropolitan Region, Thailand.</p>
</section>
<section id="install-and-launching-r-packages." class="level2">
<h2 class="anchored" data-anchor-id="install-and-launching-r-packages.">2.2 Install and Launching R packages.</h2>
<p>In this take Home exercise 1, multiple R packages will be used to perform various geospatial and statistical analyses, including spatial point pattern analysis, data manipulation, and visualization. The required R packages are as follows:</p>
<ul>
<li><p><strong>spNetwork</strong>: This package provides functions for conducting Spatial Point Patterns Analysis, such as kernel density estimation (KDE) and K-function on networks. It is also useful for building spatial matrices and traditional spatial analysis methods based on reticular distances.</p></li>
<li><p><strong>sf</strong>: Provides functions to manage, process, and manipulate Simple Features, a formal geospatial data standard that specifies the storage and access model of spatial geometries, including points, lines, and polygons.</p></li>
<li><p><strong>tmap</strong>: Offers functions for plotting cartographic-quality maps and interactive maps, leveraging the Leaflet API for interactive visualizations.</p></li>
<li><p><strong>tidyverse</strong>: A collection of packages designed for data science, including tools for data manipulation (dplyr), tidying (tidyr), and visualization (ggplot2).</p></li>
<li><p><strong>spatstat</strong>: A package for analyzing spatial point patterns, offering tools for modeling spatial data.</p></li>
<li><p><strong>ggplot2</strong>: A system for declaratively creating graphics, based on the grammar of graphics.</p></li>
<li><p><strong>leaflet</strong>: Facilitates the creation of interactive maps directly in R, supporting a variety of map styles and data layers.</p></li>
<li><p><strong>dplyr</strong>: Part of the tidyverse, providing powerful data manipulation functions.</p></li>
<li><p><strong>lubridate</strong>: Aids in dealing with date-time data, making it easier to parse and manipulate temporal data.</p></li>
<li><p><strong>dbscan</strong>: Used for density-based clustering of spatial data, often applied in identifying clusters of points, such as accident-prone areas.</p></li>
<li><p><strong>igraph</strong>: A package for network analysis, offering tools to visualize and analyze the properties of spatial networks.</p></li>
</ul>
<p>Use the following code to install and launch all necessary R packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, tmap, spNetwork, spatstat,ggplot2, leaflet, dplyr, lubridate, dbscan, igraph, dodgr,future)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="section" class="level1">
<h1></h1>
</section>
<section id="data-preparation" class="level1">
<h1>3. Data Preparation</h1>
<p>In this step, the code prepares road accident data for analysis by performing several transformations and data cleaning processes. Here’s a description of each part of the code:</p>
<ol type="1">
<li><p><strong>Loading the Dataset</strong>: The data is loaded using <code>read_csv()</code> from a CSV file called <code>thai_road_accident_2019_2022.csv</code>. This dataset contains information on road accidents in Thailand from 2019 to 2022.</p></li>
<li><p><strong>Extracting Date Information</strong>:</p>
<ul>
<li><p>The <strong>month</strong> of the accident is extracted from the <code>incident_datetime</code> column and saved as <code>Month_num</code> using the <code>month()</code> function.</p></li>
<li><p>The <strong>month</strong> is then converted to a factor (<code>Month_fac</code>) with the month names labeled and abbreviated (<code>label = TRUE, abbr = TRUE</code>).</p></li>
</ul></li>
<li><p><strong>Day of the Week</strong>: The <strong>day of the week</strong> for each accident is calculated from the <code>incident_datetime</code> column and stored as <code>dayofweek</code>.</p></li>
<li><p><strong>Filtering Missing Data</strong>: The data is filtered to remove any rows with missing <strong>longitude</strong> or <strong>latitude</strong> values (<code>filter(!is.na(longitude) &amp; !is.na(latitude))</code>), as geographical coordinates are essential for spatial analysis.</p></li>
<li><p><strong>Converting to Spatial Data</strong>: The dataset is converted into a <strong>Simple Features (sf)</strong> object using <code>st_as_sf()</code>. The function defines the <strong>coordinates</strong> as the columns <code>longitude</code> and <code>latitude</code>, with the coordinate reference system (CRS) set to <strong>EPSG: 4326</strong> (WGS84, a common geographic coordinate system).</p></li>
<li><p><strong>Reprojecting Data</strong>: The spatial data is transformed to a new CRS (projected coordinate system) using <code>st_transform(crs = 32647)</code> which is the <strong>UTM Zone 47N</strong>, a projection commonly used for Thailand.</p></li>
</ol>
<p>This process prepares the data for further spatial analysis by cleaning, extracting necessary temporal information, and transforming it into a usable geospatial format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#! eval:false</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>acc <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rawdata/thai_road_accident_2019_2022.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_num =</span> <span class="fu">month</span>(incident_datetime)) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_fac =</span> <span class="fu">month</span>(incident_datetime,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">label =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">abbr =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dayofweek =</span> <span class="fu">weekdays</span>(incident_datetime))<span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(longitude) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(latitude)) <span class="sc">%&gt;%</span>  <span class="co"># Remove rows with missing coordinates</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                       <span class="at">crs=</span><span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32647</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="filtering-data-for-bangkok-metropolitan-region-bmr" class="level2">
<h2 class="anchored" data-anchor-id="filtering-data-for-bangkok-metropolitan-region-bmr">3.1 Filtering Data for Bangkok Metropolitan Region (BMR)</h2>
<p>This code filters the road accident dataset (<code>acc</code>) to include only accidents that occurred within the <strong>Bangkok Metropolitan Region (BMR)</strong>. The filtering is done by selecting specific provinces from the <code>province_en</code> column that correspond to the BMR area:</p>
<ul>
<li><p>Bangkok</p></li>
<li><p>Nonthaburi</p></li>
<li><p>Nakhon Pathom</p></li>
<li><p>Pathum Thani</p></li>
<li><p>Samut Prakan</p></li>
<li><p>Samut Sakhon</p></li>
</ul>
<p>The result is stored in a new dataset called <code>BMR_acc</code>, which contains only the accident records from these provinces. This step ensures that subsequent analysis focuses exclusively on the BMR region, aligning with the objectives of the geospatial analysis task.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>BMR_acc <span class="ot">&lt;-</span> acc <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Nakhon Pathom"</span>, </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Pathum Thani"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Samut Sakhon"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="saving-the-filtered-data" class="level2">
<h2 class="anchored" data-anchor-id="saving-the-filtered-data">3.2 Saving the Filtered Data</h2>
<p>In this step, the filtered dataset <code>BMR_acc</code> is saved to an RDS file using the <code>write_rds()</code> function. The file is saved at the specified path: <code>"data/rds/BMR_acc_data.rds"</code>.</p>
<p>This allows the user to store the dataset and load it later for further analysis without needing to filter the data again. The RDS format is efficient for saving R objects, preserving both the structure and data of the <code>BMR_acc</code> dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(BMR_acc, <span class="st">"data/rds/BMR_acc_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-the-filtered-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-the-filtered-data">3.3 Loading the Filtered Data</h2>
<p>In this step, the saved RDS file containing the filtered Bangkok Metropolitan Region accident data (<code>BMR_acc_data.rds</code>) is loaded back into R using the <code>read_rds()</code> function. The data is assigned to the object <code>BMR_acc_data</code>.</p>
<p>This allows for easy access to the previously saved dataset without the need to repeat the filtering and transformation steps, making the workflow more efficient. The file path <code>"data/rds/BMR_acc_data.rds"</code> points to the location where the data was saved in the earlier step.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>BMR_acc_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/BMR_acc_data.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="loading-road-network-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-road-network-data">3.4 Loading Road Network Data</h2>
<p>In this step, the road network data is being read into R using the <code>st_read()</code> function from the <strong>sf</strong> package. This function reads spatial data from a shapefile.</p>
<ul>
<li><p>The <code>dsn</code> parameter specifies the directory where the raw data is located: <code>"data/rawdata"</code>.</p></li>
<li><p>The <code>layer</code> parameter identifies the specific shapefile layer being loaded: <code>"hotosm_tha_roads_lines_shp"</code>.</p></li>
</ul>
<p>The result is stored in the object <code>thai_one_map</code>, which will contain the road network data in a spatial format, ready for spatial analysis or mapping tasks.</p>
<p>This step ensures that the road network can be used alongside the accident data for conducting network-based spatial point pattern analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>thai_one_map <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/rawdata"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">layer =</span> <span class="st">"hotosm_tha_roads_lines_shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `hotosm_tha_roads_lines_shp' from data source 
  `D:\SMUJunJie\ISSS626-GAA\Take-Home_Ex\Take-Home_Ex01\data\rawdata' 
  using driver `ESRI Shapefile'
Simple feature collection with 2792590 features and 14 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 97.34457 ymin: 5.643645 xmax: 105.6528 ymax: 20.47168
CRS:           NA</code></pre>
</div>
</div>
</section>
<section id="loading-administrative-boundaries-data" class="level2">
<h2 class="anchored" data-anchor-id="loading-administrative-boundaries-data">3.5 Loading Administrative Boundaries Data</h2>
<p>In this step, administrative boundary data is loaded into R using the <code>st_read()</code> function from the <strong>sf</strong> package. This function reads spatial data from a shapefile, and the data is stored in the <code>admin_boundaries</code> object.</p>
<ul>
<li><p>The <code>dsn</code> parameter points to the directory containing the shapefile: <code>"data/rawdata"</code>.</p></li>
<li><p>The <code>layer</code> parameter specifies the specific shapefile layer to be loaded: <code>"tha_admbnda_adm1_rtsd_20220121"</code>.</p></li>
</ul>
<p>This dataset likely contains the administrative boundaries of Thailand at the <strong>first administrative level</strong>, which could be provinces or regions. These boundaries can be used for geospatial analysis or visualization alongside the road network and accident data, providing a spatial context for the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>admin_boundaries <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/rawdata"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">layer =</span> <span class="st">"tha_admbnda_adm1_rtsd_20220121"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `tha_admbnda_adm1_rtsd_20220121' from data source 
  `D:\SMUJunJie\ISSS626-GAA\Take-Home_Ex\Take-Home_Ex01\data\rawdata' 
  using driver `ESRI Shapefile'
Simple feature collection with 77 features and 16 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 97.34336 ymin: 5.613038 xmax: 105.637 ymax: 20.46507
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
<section id="filtering-administrative-boundaries-for-bmr-provinces" class="level2">
<h2 class="anchored" data-anchor-id="filtering-administrative-boundaries-for-bmr-provinces">3.6 Filtering Administrative Boundaries for BMR Provinces</h2>
<p>In this step, the administrative boundaries for each province within the Bangkok Metropolitan Region (BMR) are filtered from the <code>admin_boundaries</code> dataset. The <code>filter()</code> function is used to select boundaries for specific provinces by matching the <code>ADM1_EN</code> column (which contains the English names of provinces) with the relevant province names. The filtered boundaries are stored in separate objects for each province:</p>
<ul>
<li><p><strong>Bangkok</strong>: Stored in <code>bangkok_boundary</code>.</p></li>
<li><p><strong>Nonthaburi</strong>: Stored in <code>nonthaburi_boundary</code>.</p></li>
<li><p><strong>Nakhon Pathom</strong>: Stored in <code>nakhon_pathom_boundary</code>.</p></li>
<li><p><strong>Pathum Thani</strong>: Stored in <code>pathum_thani_boundary</code>.</p></li>
<li><p><strong>Samut Prakan</strong>: Stored in <code>samut_prakan_boundary</code>.</p></li>
<li><p><strong>Samut Sakhon</strong>: Stored in <code>samut_sakhon_boundary</code>.</p></li>
</ul>
<p>These boundary objects can be used for geospatial visualization or analysis, allowing for province-specific analysis or mapping of road accidents within each of these regions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>bangkok_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Bangkok"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>Nonthaburi_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Nonthaburi"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>Nakhon_Pathom_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Nakhon Pathom"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>Pathum_Thani_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Pathum Thani"</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>Samut_Prakan_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Samut Prakan"</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>Samut_Sakhon_boundary <span class="ot">&lt;-</span> admin_boundaries <span class="sc">%&gt;%</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ADM1_EN <span class="sc">==</span> <span class="st">"Samut Sakhon"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="setting-coordinate-reference-system-crs" class="level2">
<h2 class="anchored" data-anchor-id="setting-coordinate-reference-system-crs">3.7Setting Coordinate Reference System (CRS)</h2>
<p>In this step, the <strong>Coordinate Reference System (CRS)</strong> of the <code>thai_one_map</code> dataset is set to <strong>EPSG: 4326</strong> using the <code>st_crs()</code> function from the <strong>sf</strong> package.</p>
<ul>
<li><strong>EPSG: 4326</strong> is the geographic coordinate system based on the World Geodetic System 1984 (WGS 84), which represents data using latitude and longitude.</li>
</ul>
<p>This step ensures that the spatial data in <code>thai_one_map</code> is correctly projected and can be aligned with other datasets or maps using the same CRS, such as accident data or administrative boundaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(thai_one_map) <span class="ot">&lt;-</span> <span class="dv">4326</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="intersecting-road-network-with-administrative-boundaries" class="level2">
<h2 class="anchored" data-anchor-id="intersecting-road-network-with-administrative-boundaries">3.8 Intersecting Road Network with Administrative Boundaries</h2>
<p>In this step, the road network data (<code>thai_one_map</code>) is intersected with the administrative boundaries of each province in the Bangkok Metropolitan Region (BMR) to isolate the road segments within each province. The <code>st_intersection()</code> function is used to perform these spatial intersections.</p>
<ul>
<li><p><strong>Bangkok roads</strong>: Intersection between <code>thai_one_map</code> and <code>bangkok_boundary</code>, resulting in road segments within Bangkok.</p></li>
<li><p><strong>Nonthaburi roads</strong>: Intersection between <code>thai_one_map</code> and <code>nonthaburi_boundary</code>.</p></li>
<li><p><strong>Nakhon Pathom roads</strong>: Intersection between <code>thai_one_map</code> and <code>nakhon_pathom_boundary</code>.</p></li>
<li><p><strong>Pathum Thani roads</strong>: Intersection between <code>thai_one_map</code> and <code>pathum_thani_boundary</code>.</p></li>
<li><p><strong>Samut Prakan roads</strong>: Intersection between <code>thai_one_map</code> and <code>samut_prakan_boundary</code>.</p></li>
<li><p><strong>Samut Sakhon roads</strong>: Intersection between <code>thai_one_map</code> and <code>samut_sakhon_boundary</code>.</p></li>
</ul>
<p>This step allows for focusing the road network analysis on each specific province within BMR. It prepares the data for further spatial analysis or visualization of road accidents within each region.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>BMR_acc <span class="ot">&lt;-</span> acc <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(province_en <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Bangkok"</span>, <span class="st">"Nonthaburi"</span>, <span class="st">"Nakhon Pathom"</span>, </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Pathum Thani"</span>, <span class="st">"Samut Prakan"</span>, <span class="st">"Samut Sakhon"</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>Bangkok_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, bangkok_boundary)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>Nonthaburi_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, Nonthaburi_boundary)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>Nakhon_Pathom_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, Nakhon_Pathom_boundary)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>Pathum_Thani_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, Pathum_Thani_boundary)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>Samut_Prakan_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, Samut_Prakan_boundary)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>Samut_Sakhon_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(thai_one_map, Samut_Sakhon_boundary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="geovisualisation-and-analysis" class="level1">
<h1>4. Geovisualisation and Analysis</h1>
<section id="enhancing-accident-data-with-date-components" class="level2">
<h2 class="anchored" data-anchor-id="enhancing-accident-data-with-date-components">4.1 Enhancing Accident Data with Date Components</h2>
<p>This R code snippet enhances the accident data (<code>BMR_acc_data</code>) by extracting additional date components from the <code>incident_datetime</code> column. The <code>mutate()</code> function is used to create new columns:</p>
<ul>
<li><p><strong>incident_date</strong>: Converts <code>incident_datetime</code> to a date format using <code>as.Date()</code>.</p></li>
<li><p><strong>year</strong>: Extracts the year from <code>incident_datetime</code>.</p></li>
<li><p><strong>month</strong>: Extracts the month from <code>incident_datetime</code> and labels it with the month name using <code>month(..., label = TRUE)</code>.</p></li>
<li><p><strong>day_of_week</strong>: Extracts the day of the week from <code>incident_datetime</code> and labels it with the weekday name using <code>wday(..., label = TRUE)</code>.</p></li>
</ul>
<p>These transformations provide detailed temporal information about each accident, which can be crucial for analyzing trends over time, understanding seasonal variations, or exploring the distribution of accidents by day of the week. The enriched dataset (<code>acc_data</code>) will facilitate deeper temporal analyses and visualizations related to road traffic accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>acc_data <span class="ot">&lt;-</span> BMR_acc_data <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">incident_date =</span> <span class="fu">as.Date</span>(incident_datetime),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">year</span>(incident_datetime),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">day_of_week =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-the-number-of-accidents-over-time" class="level2">
<h2 class="anchored" data-anchor-id="plotting-the-number-of-accidents-over-time">4.2 Plotting the Number of Accidents Over Time</h2>
<p>This code creates a histogram to visualize the number of road accidents over time, with each bar representing the number of accidents occurring within a 30-day bin width:</p>
<ul>
<li><p><strong>ggplot()</strong>: Initializes the plot, mapping <code>incident_date</code> to the x-axis (<code>aes(x = incident_date)</code>), representing the timeline of accidents.</p></li>
<li><p><strong>geom_histogram()</strong>: Adds a histogram layer with a bin width of 30 days. The bars are filled with blue (<code>fill = "blue"</code>) and outlined in white (<code>color = "white"</code>).</p></li>
<li><p><strong>labs()</strong>: Adds labels to the plot, setting the title to <code>"Number of Accidents Over Time"</code> and labeling the x-axis as <code>"Date"</code> and the y-axis as <code>"Number of Accidents"</code>.</p></li>
</ul>
<p>This visualization allows you to observe the distribution of accidents over time, identifying periods of high accident frequency and any temporal patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot number of accidents by year and month</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(acc_data, <span class="fu">aes</span>(<span class="at">x =</span> incident_date)) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of Accidents Over Time"</span>, <span class="at">x =</span> <span class="st">"Date"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram shows the <strong>number of road accidents</strong> over time from 2019 to early 2023. Each bar represents the number of accidents occurring over a 30-day period.</p>
<section id="observations" class="level3">
<h3 class="anchored" data-anchor-id="observations">Observations:</h3>
<ul>
<li><p>There is significant variability in the number of accidents over time, with some months experiencing over 400 accidents.</p></li>
<li><p>A noticeable peak occurs around early 2020, followed by a dip, possibly reflecting effects of external events like the COVID-19 pandemic on traffic volume and accidents.</p></li>
<li><p>Accident counts seem to rise again towards the end of 2022 and early 2023.</p></li>
</ul>
<p>This visualization provides an initial overview of how accident frequencies change over time, and it can be used to identify trends or investigate specific periods further.</p>
</section>
</section>
<section id="plotting-the-spatial-distribution-of-accidents-on-the-road-network" class="level2">
<h2 class="anchored" data-anchor-id="plotting-the-spatial-distribution-of-accidents-on-the-road-network">4.3 Plotting the Spatial Distribution of Accidents on the Road Network</h2>
<p>This code visualizes the <strong>spatial distribution of road accidents</strong> in the <strong>Bangkok Metropolitan Region (BMR)</strong> by overlaying the road network and accident points on a map using <code>ggplot()</code> and <code>geom_sf()</code>:</p>
<ul>
<li><p><strong>geom_sf()</strong> is used to plot spatial objects, where:</p>
<ul>
<li><p><strong>Bangkok roads</strong> are plotted in <strong>antiquewhite</strong>.</p></li>
<li><p><strong>Nonthaburi roads</strong> are plotted in <strong>aquamarine</strong>.</p></li>
<li><p><strong>Nakhon Pathom roads</strong> are plotted in <strong>azure</strong>.</p></li>
<li><p><strong>Pathum Thani roads</strong> are plotted in <strong>burlywood</strong>.</p></li>
<li><p><strong>Samut Prakan roads</strong> are plotted in <strong>chartreuse</strong>.</p></li>
<li><p><strong>Samut Sakhon roads</strong> are plotted in <strong>gray</strong>.</p></li>
</ul></li>
<li><p><strong>Road accidents</strong> from the <code>BMR_acc_data</code> dataset are plotted on top of the road network in <strong>red</strong> with a size of <strong>0.5</strong> to represent individual accident points.</p></li>
<li><p>The <strong>title</strong> of the plot is set to “Spatial Distribution of Road Accidents in BMR”.</p></li>
</ul>
<p>This plot will display the accident locations overlaid on the road network of the different provinces within the BMR, helping to visually identify accident-prone areas or road segments with frequent accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the spatial distribution of accidents on the road network</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Bangkok_roads, <span class="at">color =</span> <span class="st">"antiquewhite"</span>) <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Nonthaburi_roads, <span class="at">color =</span><span class="st">"aquamarine"</span>) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Nakhon_Pathom_roads, <span class="at">color =</span> <span class="st">"azure"</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Pathum_Thani_roads, <span class="at">color =</span> <span class="st">"burlywood"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Samut_Prakan_roads, <span class="at">color =</span> <span class="st">"chartreuse"</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> Samut_Sakhon_roads, <span class="at">color =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> BMR_acc_data, <span class="fu">aes</span>(<span class="at">geometry =</span> geometry), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Spatial Distribution of Road Accidents in BMR"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The map you’ve generated provides a visual representation of the <strong>spatial distribution of road accidents</strong> in the <strong>Bangkok Metropolitan Region (BMR)</strong>, with the road networks of different provinces overlaid in various colors:</p>
<ul>
<li><p><strong>Bangkok</strong> roads are plotted in <strong>antiquewhite</strong>.</p></li>
<li><p><strong>Nonthaburi</strong> roads are in <strong>aquamarine</strong>.</p></li>
<li><p><strong>Nakhon Pathom</strong> roads are in <strong>azure</strong>.</p></li>
<li><p><strong>Pathum Thani</strong> roads are in <strong>burlywood</strong>.</p></li>
<li><p><strong>Samut Prakan</strong> roads are in <strong>chartreuse</strong>.</p></li>
<li><p><strong>Samut Sakhon</strong> roads are in <strong>gray</strong>.</p></li>
</ul>
<p>The red points represent the locations of road accidents across the region, clearly highlighting accident clusters and areas with high traffic incidents. This visualization allows you to quickly identify road segments with frequent accidents, as well as compare accident density across different provinces in BMR.</p>
</section>
<section id="creating-a-heatmap-of-accidents-by-hour-of-day-and-day-of-the-week" class="level2">
<h2 class="anchored" data-anchor-id="creating-a-heatmap-of-accidents-by-hour-of-day-and-day-of-the-week">4.4 Creating a Heatmap of Accidents by Hour of Day and Day of the Week</h2>
<p>This code generates a heatmap to visualize the distribution of road accidents based on the <strong>hour of the day</strong> and the <strong>day of the week</strong>.</p>
<section id="step-1-extract-hour-of-day-and-day-of-week" class="level4">
<h4 class="anchored" data-anchor-id="step-1-extract-hour-of-day-and-day-of-week">Step 1: Extract Hour of Day and Day of Week</h4>
<ul>
<li><p>The <code>mutate()</code> function is used to create two new columns in <code>acc_data</code>:</p>
<ul>
<li><p><code>hour_of_day</code>: Extracts the hour from <code>incident_datetime</code> using the <code>hour()</code> function.</p></li>
<li><p><code>day_of_week</code>: Extracts the day of the week using <code>wday(label = TRUE)</code>, with labels for easier interpretation.</p></li>
</ul></li>
</ul>
</section>
<section id="step-2-summarize-data-by-hour-and-day" class="level4">
<h4 class="anchored" data-anchor-id="step-2-summarize-data-by-hour-and-day">Step 2: Summarize Data by Hour and Day</h4>
<ul>
<li>The data is grouped by both <code>hour_of_day</code> and <code>day_of_week</code> using <code>group_by()</code>, and the number of accidents is counted for each combination using <code>summarise()</code>.</li>
</ul>
</section>
<section id="step-3-create-the-heatmap" class="level4">
<h4 class="anchored" data-anchor-id="step-3-create-the-heatmap">Step 3: Create the Heatmap</h4>
<ul>
<li><p>The heatmap is created using <code>ggplot()</code>, where:</p>
<ul>
<li><p><strong>x-axis</strong>: Represents the <code>hour_of_day</code>.</p></li>
<li><p><strong>y-axis</strong>: Represents the <code>day_of_week</code>.</p></li>
<li><p><strong>fill</strong>: Represents the count of accidents for each hour-day combination.</p></li>
</ul></li>
<li><p><strong>geom_tile()</strong>: Creates the heatmap tiles, where each tile’s color represents the accident count.</p></li>
<li><p><strong>scale_fill_gradient()</strong>: The color gradient is set from white (low count) to red (high count) to emphasize areas with more accidents.</p></li>
<li><p><strong>labs()</strong>: Sets the title and axis labels.</p></li>
<li><p><strong>theme_minimal()</strong>: Applies a minimal theme for a clean look.</p></li>
</ul>
<p>This heatmap provides insights into the busiest accident times during the week, highlighting patterns such as peak hours or specific days with a high frequency of accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Extract hour of the day and day of the week for accidents</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>acc_data <span class="ot">&lt;-</span> acc_data <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hour_of_day =</span> <span class="fu">hour</span>(incident_datetime),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">day_of_week =</span> <span class="fu">wday</span>(incident_datetime, <span class="at">label =</span> <span class="cn">TRUE</span>))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Summarize the data by hour of day and day of week</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>summary_data <span class="ot">&lt;-</span> acc_data <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(hour_of_day, day_of_week) <span class="sc">%&gt;%</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())  <span class="co"># Count the number of accidents for each combination</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Create a heatmap of accidents by hour and day of week</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(summary_data, <span class="fu">aes</span>(<span class="at">x =</span> hour_of_day, <span class="at">y =</span> day_of_week, <span class="at">fill =</span> count)) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Heatmap of Accidents by Hour of Day and Day of Week"</span>, </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Hour of Day"</span>, <span class="at">y =</span> <span class="st">"Day of Week"</span>) <span class="sc">+</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This heatmap visualizes the number of road accidents across different hours of the day and days of the week. The intensity of the color represents the accident frequency, with darker red areas indicating higher counts.</p>
</section>
<section id="observations-1" class="level3">
<h3 class="anchored" data-anchor-id="observations-1">Observations:</h3>
<ul>
<li><p><strong>Peak Accident Times</strong>: There are two notable peaks, one in the late morning around <strong>10 AM</strong> and another during the <strong>evening hours</strong> around <strong>8 PM</strong>.</p></li>
<li><p><strong>Day of the Week</strong>: Accidents tend to occur consistently throughout the week, with <strong>Friday</strong> (周五) and <strong>Saturday</strong> (周六) having slightly higher accident counts in the evening compared to other days.</p></li>
<li><p><strong>Early Morning</strong>: Fewer accidents are recorded during the early morning hours (midnight to around 6 AM), as indicated by the lighter shading.</p></li>
</ul>
</section>
</section>
<section id="extracting-the-month-from-the-incident-date" class="level2">
<h2 class="anchored" data-anchor-id="extracting-the-month-from-the-incident-date">4.5 Extracting the Month from the Incident Date</h2>
<p>In this step, the code is extracting the <strong>month</strong> from the <code>incident_datetime</code> column in the <code>BMR_acc_data</code> dataset and creating a new column called <code>month</code>. The <code>mutate()</code> function is used to add this new variable, where the <code>month()</code> function extracts the month component from the <code>incident_datetime</code>.</p>
<p>This transformation allows for further analysis of accident trends by month, helping to explore any seasonal patterns in road accidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>acc_data <span class="ot">&lt;-</span> BMR_acc_data <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">month</span>(incident_datetime))  <span class="co"># Extract month from incident datetime</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plotting-monthly-accident-counts-over-time" class="level2">
<h2 class="anchored" data-anchor-id="plotting-monthly-accident-counts-over-time">4.6 Plotting Monthly Accident Counts Over Time</h2>
<p>This code creates a <strong>time series plot</strong> to visualize the monthly number of road accidents over time:</p>
<section id="step-1-extract-year-and-month" class="level4">
<h4 class="anchored" data-anchor-id="step-1-extract-year-and-month">Step 1: Extract Year and Month</h4>
<ul>
<li>The <code>mutate()</code> function is used to extract both the <strong>year</strong> and <strong>month</strong> from the <code>incident_datetime</code> column, creating new columns <code>year</code> and <code>month</code>.</li>
</ul>
</section>
<section id="step-2-summarize-data-by-year-and-month" class="level4">
<h4 class="anchored" data-anchor-id="step-2-summarize-data-by-year-and-month">Step 2: Summarize Data by Year and Month</h4>
<ul>
<li>The <code>group_by()</code> function groups the data by <code>year</code> and <code>month</code>, and the <code>summarise()</code> function counts the number of accidents for each month, creating the <code>monthly_accidents</code> dataset.</li>
</ul>
</section>
<section id="step-3-plot-the-time-series" class="level4">
<h4 class="anchored" data-anchor-id="step-3-plot-the-time-series">Step 3: Plot the Time Series</h4>
<ul>
<li><p><strong>ggplot()</strong>: Initializes the plot with:</p>
<ul>
<li><p><strong>x-axis</strong>: The combination of <code>year</code> and <code>month</code> using the <code>interaction()</code> function.</p></li>
<li><p><strong>y-axis</strong>: The monthly accident count.</p></li>
</ul></li>
<li><p><strong>geom_line()</strong>: Adds a blue line connecting the accident counts over time.</p></li>
<li><p><strong>geom_point()</strong>: Adds points on the line to mark each month’s accident count.</p></li>
<li><p><strong>labs()</strong>: Adds a title and labels the axes (“Year-Month” for the x-axis and “Number of Accidents” for the y-axis).</p></li>
<li><p><strong>theme()</strong>: Rotates the x-axis text to make it more readable, setting the angle to 90 degrees.</p></li>
</ul>
<p>This time series plot provides a clear visualization of monthly accident trends, allowing for the identification of any long-term patterns or fluctuations in road accident counts over the years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>acc_data <span class="ot">&lt;-</span> acc_data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">year</span>(incident_datetime),    <span class="co"># Extract year</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(incident_datetime)   <span class="co"># Extract month</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>monthly_accidents <span class="ot">&lt;-</span> acc_data <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, month) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot time series of accidents</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(monthly_accidents, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">interaction</span>(year, month, <span class="at">sep =</span> <span class="st">"-"</span>), <span class="at">y =</span> count, <span class="at">group =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Monthly Accident Counts Over Time"</span>, <span class="at">x =</span> <span class="st">"Year-Month"</span>, <span class="at">y =</span> <span class="st">"Number of Accidents"</span>) <span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This time series plot shows the <strong>monthly accident counts</strong> over the period from January 2019 to December 2022.</p>
</section>
<section id="observations-2" class="level3">
<h3 class="anchored" data-anchor-id="observations-2">Observations:</h3>
<ul>
<li><p><strong>Fluctuations</strong>: The number of accidents fluctuates throughout the period, with some peaks reaching around 350 accidents in certain months.</p></li>
<li><p><strong>Trend</strong>: There seems to be a general upward trend in accidents toward the end of the time series, especially after a noticeable dip in late 2021.</p></li>
<li><p><strong>Notable Events</strong>: There is a sharp decline in accident counts around late 2021, followed by a rapid increase. This could be associated with external factors such as reduced traffic during lockdown periods or other significant events.</p></li>
</ul>
</section>
</section>
<section id="seasonal-decomposition-of-monthly-accident-counts" class="level2">
<h2 class="anchored" data-anchor-id="seasonal-decomposition-of-monthly-accident-counts">4.7 Seasonal Decomposition of Monthly Accident Counts</h2>
<p>This code performs <strong>seasonal decomposition</strong> on the time series of monthly accident counts, which helps to break down the data into its <strong>trend</strong>, <strong>seasonal</strong>, and <strong>residual</strong> components.</p>
<section id="step-1-create-a-time-series-object" class="level4">
<h4 class="anchored" data-anchor-id="step-1-create-a-time-series-object">Step 1: Create a Time Series Object</h4>
<ul>
<li><p>The <code>ts()</code> function is used to create a time series object <code>ts_data</code> for the monthly accident counts.</p>
<ul>
<li><p>The <code>count</code> column from the <code>monthly_accidents</code> dataset is used as the data.</p></li>
<li><p>The <code>start</code> argument defines the starting year and month for the time series.</p></li>
<li><p><code>frequency = 12</code> indicates that the data is monthly (12 periods per year).</p></li>
</ul></li>
</ul>
</section>
<section id="step-2-perform-seasonal-decomposition" class="level4">
<h4 class="anchored" data-anchor-id="step-2-perform-seasonal-decomposition">Step 2: Perform Seasonal Decomposition</h4>
<ul>
<li><p>The <code>stl()</code> function performs <strong>Seasonal-Trend decomposition using LOESS (STL)</strong> on the time series <code>ts_data</code>.</p>
<ul>
<li><code>s.window = "periodic"</code> specifies that the seasonal component is to be extracted with a fixed periodicity (i.e., 12 months for monthly data).</li>
</ul></li>
</ul>
</section>
<section id="step-3-plot-the-decomposition" class="level4">
<h4 class="anchored" data-anchor-id="step-3-plot-the-decomposition">Step 3: Plot the Decomposition</h4>
<ul>
<li><p>The <code>plot()</code> function visualizes the decomposition, showing the <strong>trend</strong>, <strong>seasonality</strong>, and <strong>residuals</strong> of the monthly accident data.</p>
<ul>
<li>The main title is set to “Seasonal Decomposition of Monthly Accident Counts.”</li>
</ul></li>
</ul>
<p>This decomposition helps to analyze the underlying patterns in the data, revealing any long-term trends, recurring seasonal effects (e.g., certain months having more accidents), and any random residuals or noise that cannot be explained by the trend or seasonality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a time series object for accident counts</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(monthly_accidents<span class="sc">$</span>count, <span class="at">start =</span> <span class="fu">c</span>(<span class="fu">min</span>(monthly_accidents<span class="sc">$</span>year), <span class="fu">min</span>(<span class="fu">as.numeric</span>(monthly_accidents<span class="sc">$</span>month))), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform seasonal decomposition</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>decomp <span class="ot">&lt;-</span> <span class="fu">stl</span>(ts_data, <span class="at">s.window =</span> <span class="st">"periodic"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the decomposition</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(decomp, <span class="at">main =</span> <span class="st">"Seasonal Decomposition of Monthly Accident Counts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot displays the <strong>seasonal decomposition</strong> of monthly accident counts, breaking the data down into the following components:</p>
<ol type="1">
<li><p><strong>Data</strong> (Top Panel): The original time series showing the observed monthly accident counts.</p></li>
<li><p><strong>Seasonal Component</strong> (Second Panel): This reveals recurring patterns in the data, which repeat every 12 months (yearly cycle). You can observe consistent seasonal fluctuations, with certain months regularly showing higher or lower accident counts.</p></li>
<li><p><strong>Trend Component</strong> (Third Panel): The long-term trend in the data shows an initial decline from 2019 through mid-2021, followed by a notable increase in accident counts from late 2021 into 2023.</p></li>
<li><p><strong>Remainder (Residuals)</strong> (Bottom Panel): The residuals represent the remaining variation in the data after removing the trend and seasonal components. These fluctuations are likely due to random noise or other factors not captured by the model.</p></li>
</ol>
</section>
<section id="observations-3" class="level3">
<h3 class="anchored" data-anchor-id="observations-3">Observations:</h3>
<ul>
<li><p>The <strong>seasonal component</strong> shows a regular pattern of variation across the year, with higher accidents during certain months.</p></li>
<li><p>The <strong>trend</strong> shows a decrease during 2020 and early 2021, possibly due to reduced traffic during COVID-19 lockdowns, followed by a sharp increase starting in late 2021.</p></li>
<li><p>The <strong>residuals</strong> appear relatively small and random, suggesting that the model captures the key patterns well.</p></li>
</ul>
</section>
</section>
<section id="monthly-spatial-analysis-of-road-accident-hotspots-in-bmr-using-kde" class="level2">
<h2 class="anchored" data-anchor-id="monthly-spatial-analysis-of-road-accident-hotspots-in-bmr-using-kde">4.8 Monthly Spatial Analysis of Road Accident Hotspots in BMR Using KDE</h2>
<p>The code performs <strong>Kernel Density Estimation (KDE)</strong> on road accident data for each month and combines the results into a single data frame for further analysis or visualization.</p>
<section id="key-steps" class="level4">
<h4 class="anchored" data-anchor-id="key-steps">Key Steps:</h4>
<ol type="1">
<li><p><strong>KDE Calculation for Each Month</strong>:</p>
<ul>
<li><p>The <code>kde_for_month</code> function extracts spatial coordinates (<code>st_coordinates()</code>) from accident data and creates a bounding box (<code>as.owin()</code>) for defining the spatial window.</p></li>
<li><p>It converts the accident data into a point pattern (<code>ppp</code>) and applies Kernel Density Estimation (<code>density()</code>) with a smoothing parameter <code>sigma = 300</code>.</p></li>
<li><p>The result is transformed into a data frame (<code>as.data.frame()</code>) to be used for visualization with <code>ggplot</code>.</p></li>
</ul></li>
<li><p><strong>Suppress Duplicate Warnings</strong>:</p>
<ul>
<li>Warnings related to duplicate points in the dataset are suppressed to avoid unnecessary output.</li>
</ul></li>
<li><p><strong>Apply KDE Grouped by Month</strong>:</p>
<ul>
<li>The KDE function is applied to each month’s data using <code>group_by(Month_num)</code> and <code>group_map()</code>. This groups the dataset by month and applies the <code>kde_for_month</code> function to each group.</li>
</ul></li>
<li><p><strong>Combining KDE Results</strong>:</p>
<ul>
<li>The resulting KDE for each month is combined into a single data frame (<code>kde_combined</code>) using <code>bind_rows()</code>, with an additional <code>month</code> column to identify the corresponding month for each KDE result.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>kde_for_month <span class="ot">&lt;-</span> <span class="cf">function</span>(month_data) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extract coordinates</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(month_data<span class="sc">$</span>geometry)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># No need to remove duplicates, proceed with all coordinates</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a bounding box or window for the KDE</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(<span class="fu">st_bbox</span>(month_data))</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert to a point pattern for KDE</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  acc_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(<span class="at">x =</span> coords[,<span class="dv">1</span>], <span class="at">y =</span> coords[,<span class="dv">2</span>], <span class="at">window =</span> window)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Perform Kernel Density Estimation with an optimal sigma value</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  acc_kde <span class="ot">&lt;-</span> <span class="fu">density</span>(acc_ppp, <span class="at">sigma =</span> <span class="dv">300</span>)  <span class="co"># Adjust sigma as needed</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Convert KDE result to data frame for ggplot</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  kde_raster <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(acc_kde)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(kde_raster)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress warnings related to duplicate points</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">warn =</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate KDE for each month</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>kde_data <span class="ot">&lt;-</span> BMR_acc_data <span class="sc">%&gt;%</span></span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Month_num) <span class="sc">%&gt;%</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_map</span>(<span class="sc">~</span> <span class="fu">kde_for_month</span>(.x), <span class="at">.keep =</span> <span class="cn">TRUE</span>)  <span class="co"># Apply KDE for each group (month)</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine all KDE data</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>kde_combined <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(kde_data, <span class="at">.id =</span> <span class="st">"month"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="monthly-heatmap-of-road-accident-densities-in-bmr-using-kde" class="level2">
<h2 class="anchored" data-anchor-id="monthly-heatmap-of-road-accident-densities-in-bmr-using-kde">4.9 Monthly Heatmap of Road Accident Densities in BMR Using KDE</h2>
<p>This code creates a <strong>heatmap</strong> to visualize the <strong>Kernel Density Estimation (KDE)</strong> of road traffic accidents for each month, using <code>ggplot2</code>.</p>
<section id="key-elements" class="level4">
<h4 class="anchored" data-anchor-id="key-elements">Key Elements:</h4>
<ol type="1">
<li><p><strong>ggplot with Raster Layer (<code>geom_raster()</code>)</strong>:</p>
<ul>
<li><code>geom_raster()</code> is used to plot the KDE results, where each tile is filled based on the density values.</li>
</ul></li>
<li><p><strong>Color Scale (<code>scale_fill_viridis_c()</code>)</strong>:</p>
<ul>
<li><p>The <code>magma</code> color palette is used with a reversed direction for better contrast, visually highlighting high-density areas.</p></li>
<li><p>The <code>fill = value</code> aesthetic maps density values to color intensity.</p></li>
</ul></li>
<li><p><strong>Faceted by Month (<code>facet_wrap()</code>)</strong>:</p>
<ul>
<li>The KDE results are faceted by month using <code>facet_wrap(~ month)</code>, arranging the plots into a grid with 3 columns (<code>ncol = 3</code>).</li>
</ul></li>
<li><p><strong>Minimal Theme (<code>theme_minimal()</code>)</strong>:</p>
<ul>
<li>A minimalist design is applied, removing axis labels, ticks, and grid lines for a clean visual focus on the KDE.</li>
</ul></li>
<li><p><strong>Custom Labels</strong>:</p>
<ul>
<li>The plot title is set as <strong>“KDE of Road Traffic Accidents by Month”</strong>, and the fill color legend is labeled as <strong>“Density”</strong>.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kde_combined, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> value)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>() <span class="sc">+</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option =</span> <span class="st">"magma"</span>, <span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Magma with reverse direction for contrast</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"KDE of Road Traffic Accidents by Month"</span>, <span class="at">fill =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>General Overview</strong>:</p>
<ul>
<li><p>The <strong>heatmap</strong> panels display the spatial distribution of road accident densities across each month in the Bangkok Metropolitan Region (BMR).</p></li>
<li><p>The intensity of red indicates <strong>high-density</strong> areas where accidents are more frequent, while yellow represents <strong>low-density</strong> areas.</p></li>
<li><p>The color scale on the right, ranging from <strong>0</strong> to around <strong>2e-05</strong>, shows the density values, with darker regions indicating more accident-prone areas.</p></li>
</ul></li>
<li><p><strong>Consistent Hotspots</strong>:</p>
<ul>
<li><p>There appear to be <strong>consistent accident hotspots</strong> across multiple months, especially around key intersections and high-traffic zones in central regions.</p></li>
<li><p>These hotspots are visible in nearly all months (e.g., months 1, 4, 7, and 12), suggesting <strong>persistent high-risk zones</strong> in the BMR, which could be due to road layout, traffic volume, or hazardous conditions.</p></li>
</ul></li>
<li><p><strong>Seasonal Variation</strong>:</p>
<ul>
<li><p>Although the overall pattern of accident distribution seems similar across months, the <strong>intensity of hotspots</strong> may vary slightly between certain months.</p></li>
<li><p>Some months, such as <strong>October (10)</strong> and <strong>December (12)</strong>, show slightly more intense hotspot activity than others, potentially correlating with changes in traffic patterns due to holidays or seasonal weather conditions.</p></li>
</ul></li>
<li><p><strong>Low Density Areas</strong>:</p>
<ul>
<li><p>A significant portion of the BMR has <strong>very low accident densities</strong>, as indicated by the vast yellow regions on the heatmap.</p></li>
<li><p>These areas may represent residential or less congested zones with lower accident frequencies, or areas with fewer road users during certain months.</p></li>
</ul></li>
<li><p><strong>Implications for Traffic Management</strong>:</p>
<ul>
<li><p>The identification of consistent accident hotspots suggests areas where <strong>increased traffic enforcement</strong>, <strong>road safety measures</strong>, or <strong>infrastructure improvements</strong> may be necessary.</p></li>
<li><p>Authorities can focus on these high-density zones for further investigation into accident causes and potential safety interventions.</p></li>
</ul></li>
<li><p><strong>Further Investigation</strong>:</p>
<ul>
<li>The variations in density between months could be explored further by comparing external factors, such as <strong>weather patterns</strong>, <strong>road conditions</strong>, and <strong>holiday seasons</strong>, to see if these contribute to the observed changes in accident density.</li>
</ul></li>
</ul>
</section>
</section>
<section id="preparing-spatial-accident-data-for-point-pattern-analysis-in-bmr" class="level2">
<h2 class="anchored" data-anchor-id="preparing-spatial-accident-data-for-point-pattern-analysis-in-bmr">4.10 Preparing Spatial Accident Data for Point Pattern Analysis in BMR</h2>
<p>This code prepares the road accident data for <strong>spatial point pattern analysis</strong> by converting it into a format compatible with the <strong>spatstat</strong> package in R. Here’s a breakdown of the key steps:</p>
<ol type="1">
<li><p><strong>Suppress Warnings</strong>:</p>
<ul>
<li><code>options(warn = -1)</code> disables warnings related to duplicate points, which may occur when dealing with spatial data.</li>
</ul></li>
<li><p><strong>Extract Spatial Coordinates</strong>:</p>
<ul>
<li><code>st_coordinates(acc_data$geometry)</code> extracts the spatial coordinates (longitude and latitude) from the <code>geometry</code> column in the <code>acc_data</code> dataset.</li>
</ul></li>
<li><p><strong>Create a Window (Bounding Box)</strong>:</p>
<ul>
<li><code>as.owin(st_bbox(acc_data))</code> creates a <strong>bounding box</strong> around the study area, which will be used as the spatial window for the analysis. The bounding box is converted into an observation window using <code>as.owin()</code>.</li>
</ul></li>
<li><p><strong>Convert to Point Pattern (<code>ppp</code>)</strong>:</p>
<ul>
<li>The accident data is converted into a <strong>point pattern</strong> object using the <code>ppp()</code> function, where the x and y coordinates (longitude and latitude) are input along with the study area’s window. This format is essential for conducting further spatial analyses, such as <strong>Kernel Density Estimation (KDE)</strong> or <strong>spatial clustering</strong>.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">warn =</span> <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the spatial coordinates from the geometry column</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(acc_data<span class="sc">$</span>geometry)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a window (bounding box) for your study area</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>window <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(<span class="fu">st_bbox</span>(acc_data))</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the accident data to a point pattern (ppp) object for spatstat</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>acc_ppp <span class="ot">&lt;-</span> <span class="fu">ppp</span>(<span class="at">x =</span> coords[, <span class="dv">1</span>], <span class="at">y =</span> coords[, <span class="dv">2</span>], <span class="at">window =</span> window)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analyzing-spatial-clustering-of-road-accidents-using-ripleys-k-function" class="level2">
<h2 class="anchored" data-anchor-id="analyzing-spatial-clustering-of-road-accidents-using-ripleys-k-function">4.11 Analyzing Spatial Clustering of Road Accidents Using Ripley’s K-function</h2>
<p>This code performs a <strong>K-function analysis</strong> (Ripley’s K-function) on road accident data, which is useful for understanding the spatial distribution of accidents and identifying clustering patterns. Here’s a breakdown:</p>
<ol type="1">
<li><p><strong>K-function Calculation</strong>:</p>
<ul>
<li><code>Kest(acc_ppp)</code> computes Ripley’s K-function on the point pattern object <code>acc_ppp</code>. The K-function measures the spatial clustering of points over a range of distances, helping to determine whether points (accidents) are clustered, randomly distributed, or dispersed at different scales.</li>
</ul></li>
<li><p><strong>Plot the K-function</strong>:</p>
<ul>
<li><p>The <code>plot()</code> function visualizes the result of the K-function analysis.</p></li>
<li><p>The plot’s title is set as <strong>“Ripley’s K-function for Road Accidents”</strong>, and the legend is positioned in the top right using <code>legendargs = list(x = "topright")</code>.</p></li>
</ul></li>
</ol>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation:</h3>
<ul>
<li>The K-function plot will show how accident clustering behaves at different distances. If the K-function line is above the expected value for a random distribution, it indicates clustering. If it’s below, it suggests dispersion.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform K-function analysis</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>k_function <span class="ot">&lt;-</span> <span class="fu">Kest</span>(acc_ppp)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the result</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(k_function, <span class="at">main =</span> <span class="st">"Ripley's K-function for Road Accidents"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">legendargs =</span> <span class="fu">list</span>(<span class="at">x =</span> <span class="st">"topright"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot illustrates Ripley’s K-function, which analyzes the spatial distribution of road accidents and helps determine whether they are clustered, randomly distributed, or dispersed over space.</p>
<section id="key-observations" class="level4">
<h4 class="anchored" data-anchor-id="key-observations">Key Observations:</h4>
<ol type="1">
<li><p><strong>Black Line (Observed K-function)</strong>:</p>
<ul>
<li><p>The black line represents the K-function for the actual accident data.</p></li>
<li><p>A rapid increase in the K-function suggests that road accidents are <strong>highly clustered</strong>.</p></li>
<li><p>The clustering effect is particularly noticeable at smaller distances and persists as the distance increases.</p></li>
</ul></li>
<li><p><strong>Red Dashed Line (Poisson Process)</strong>:</p>
<ul>
<li><p>The red dashed line represents the expected K-function if the accidents were randomly distributed (Poisson process).</p></li>
<li><p>The observed K-function (black line) is consistently <strong>above</strong> the Poisson process, which indicates that road accidents are not randomly distributed but are <strong>spatially clustered</strong>.</p></li>
</ul></li>
<li><p><strong>Distance</strong>:</p>
<ul>
<li><p>As the distance <strong>r</strong> increases (on the x-axis), the K-function continues to rise sharply, showing that clustering occurs over both small and larger spatial scales.</p></li>
<li><p>This suggests that there are accident-prone zones where road accidents occur close to one another, and this clustering persists over extended areas.</p></li>
</ul></li>
</ol>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion:</h4>
<p>Ripley’s K-function confirms that road accidents are <strong>spatially clustered</strong> in the study area. The clustering is evident at both small and large distances, indicating the presence of high-risk zones where accidents are more frequent. Understanding this spatial clustering is essential for developing targeted safety interventions, such as traffic control measures or infrastructure improvements in accident hotspots.</p>
</section>
</section>
</section>
<section id="monte-carlo-simulation-for-validating-road-accident-clustering-using-ripleys-k-function" class="level2">
<h2 class="anchored" data-anchor-id="monte-carlo-simulation-for-validating-road-accident-clustering-using-ripleys-k-function">4.12 Monte Carlo Simulation for Validating Road Accident Clustering Using Ripley’s K-function</h2>
<p>This code performs <strong>Monte Carlo simulations</strong> to generate an <strong>envelope</strong> for Ripley’s K-function. The envelope is used to compare the observed clustering pattern of road accidents with a <strong>Complete Spatial Randomness (CSR)</strong> pattern, which helps in determining if the observed clustering is statistically significant.</p>
<section id="key-steps-1" class="level4">
<h4 class="anchored" data-anchor-id="key-steps-1">Key Steps:</h4>
<ol type="1">
<li><p><strong>Monte Carlo Simulations</strong>:</p>
<ul>
<li><p>The <code>envelope()</code> function is applied to the point pattern <code>acc_ppp</code> with the <code>Kest</code> function. This function generates a range of expected K-functions based on 99 random simulations (<code>nsim = 99</code>), assuming the accidents are distributed according to CSR.</p></li>
<li><p>CSR serves as a baseline or null hypothesis, which assumes that the points (road accidents) are randomly distributed in space.</p></li>
</ul></li>
<li><p><strong>K-function Envelope</strong>:</p>
<ul>
<li>The result (<code>envelope_k</code>) is an <strong>envelope</strong> that includes a lower and upper bound based on the Monte Carlo simulations. The observed K-function can be compared against this envelope to assess whether the clustering pattern is significantly different from randomness.</li>
</ul></li>
</ol>
</section>
<section id="interpretation-1" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-1">Interpretation:</h4>
<ul>
<li>If the observed K-function lies <strong>outside</strong> the envelope, this indicates that the observed spatial pattern is significantly different from what would be expected under CSR, suggesting <strong>significant clustering</strong> or <strong>dispersion</strong>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform Monte Carlo simulations to compare with CSR</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>envelope_k <span class="ot">&lt;-</span> <span class="fu">envelope</span>(acc_ppp, Kest, <span class="at">nsim =</span> <span class="dv">99</span>)  <span class="co"># Perform 99 simulations for CSR</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generating 99 simulations of CSR  ...
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 
99.

Done.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the envelope of the K-function (observed vs CSR)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(envelope_k, <span class="at">main =</span> <span class="st">"K-function with CSR Envelope"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows the comparison between the <strong>observed K-function</strong> for road accidents and the <strong>CSR envelope</strong> generated from Monte Carlo simulations. The plot helps in assessing whether the observed spatial pattern of road accidents is significantly different from a random distribution.</p>
</section>
<section id="key-components" class="level4">
<h4 class="anchored" data-anchor-id="key-components">Key Components:</h4>
<ol type="1">
<li><p><strong>Black Line (<code>K_obs(r)</code>)</strong>:</p>
<ul>
<li><p>This represents the observed K-function for the road accident data.</p></li>
<li><p>The line shows how road accidents are spatially clustered at various distances, with larger values of <code>r</code> on the x-axis corresponding to greater distances between points.</p></li>
</ul></li>
<li><p><strong>Dashed Red Line (<code>K_theo(r)</code>)</strong>:</p>
<ul>
<li>This represents the theoretical K-function under <strong>Complete Spatial Randomness (CSR)</strong>. It serves as a baseline to compare the observed clustering against a random spatial distribution of points.</li>
</ul></li>
<li><p><strong>Gray Shaded Envelope</strong> (<code>K_hi(r)</code> and <code>K_lo(r)</code>):</p>
<ul>
<li><p>The envelope is the range of expected values from the Monte Carlo simulations (99 simulations).</p></li>
<li><p>If the observed K-function (black line) lies <strong>outside</strong> this envelope, it suggests that the observed pattern is significantly different from randomness.</p></li>
</ul></li>
</ol>
</section>
<section id="interpretation-2" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-2">Interpretation:</h4>
<ul>
<li><p>The observed K-function (black line) is <strong>consistently above the upper boundary</strong> of the CSR envelope, indicating significant <strong>spatial clustering</strong> of road accidents.</p></li>
<li><p>This suggests that the clustering of road accidents is not due to random chance but likely due to underlying factors such as road conditions, traffic patterns, or intersection density.</p></li>
<li><p>The K-function continues to rise steeply as the distance increases, showing that the clustering persists over larger distances.</p></li>
</ul>
</section>
</section>
</section>
<section id="ndke-analysis" class="level1">
<h1>5. NDKE Analysis</h1>
<section id="geospatial-analysis-of-bangkok-road-accidents." class="level2">
<h2 class="anchored" data-anchor-id="geospatial-analysis-of-bangkok-road-accidents.">5.1 Geospatial analysis of Bangkok road accidents.</h2>
<p>three datasets are assigned to variables:</p>
<ol type="1">
<li><p><strong>bangkok_acc_data</strong>: Accident data for the Bangkok Metropolitan Region, assigned from <strong>BMR_acc_data</strong>.</p></li>
<li><p><strong>bangkok_boundary</strong>: Geographic boundary data for Bangkok.</p></li>
<li><p><strong>bangkok_roads</strong>: Road network data for Bangkok.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use your dataset names</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>bangkok_acc_data <span class="ot">&lt;-</span> BMR_acc_data</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>bangkok_boundary <span class="ot">&lt;-</span> bangkok_boundary</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>bangkok_roads <span class="ot">&lt;-</span> Bangkok_roads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="crs-transformation-for-spatial-data-in-road-accident-analysis" class="level2">
<h2 class="anchored" data-anchor-id="crs-transformation-for-spatial-data-in-road-accident-analysis">5.2 CRS Transformation for Spatial Data in Road Accident Analysis</h2>
<p>The code shown here is performing a <strong>coordinate reference system (CRS) transformation</strong> for spatial datasets related to road accidents and road networks in Bangkok. This step ensures that all spatial data is using the same CRS for accurate analysis and visualization.</p>
<section id="key-steps-2" class="level4">
<h4 class="anchored" data-anchor-id="key-steps-2">Key Steps:</h4>
<ol type="1">
<li><p><strong>Target CRS (<code>32647</code>)</strong>:</p>
<ul>
<li>The target CRS is set to <strong>UTM Zone 47N</strong> (EPSG: 32647), which is appropriate for spatial data in Bangkok, ensuring accurate distance and area calculations.</li>
</ul></li>
<li><p><strong>CRS Transformation (<code>st_transform</code>)</strong>:</p>
<ul>
<li><p>The function <code>st_transform()</code> is used to project each spatial dataset into the specified CRS:</p>
<ul>
<li><p><code>bangkok_acc_data</code>: Road accident data for Bangkok.</p></li>
<li><p><code>bangkok_roads</code>: Road network data for Bangkok.</p></li>
<li><p><code>bangkok_boundary</code>: Administrative boundary data for Bangkok.</p></li>
</ul></li>
</ul></li>
</ol>
<p>This transformation is necessary because spatial datasets often come with different CRS, and for accurate geospatial analysis (e.g., distance measurements, KDE), all datasets must be in the same projection.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>target_crs <span class="ot">&lt;-</span> <span class="dv">32647</span>  <span class="co"># UTM Zone 47N</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>bangkok_acc_data <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bangkok_acc_data, <span class="at">crs =</span> target_crs)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>bangkok_roads <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bangkok_roads, <span class="at">crs =</span> target_crs)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>bangkok_boundary <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(bangkok_boundary, <span class="at">crs =</span> target_crs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="preprocessing-road-network-data-filtering-and-geometry-casting-in-geospatial-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preprocessing-road-network-data-filtering-and-geometry-casting-in-geospatial-analysis">5.3 Preprocessing Road Network Data: Filtering and Geometry Casting in Geospatial Analysis</h2>
<p>This code snippet processes the road network data for Bangkok, ensuring that only the relevant geometry types are retained and properly formatted for further geospatial analysis. Here’s a breakdown:</p>
<ol type="1">
<li><p><strong>Filter Geometry Types</strong>:</p>
<ul>
<li>The first part of the code filters the road network dataset (<code>bangkok_roads</code>) to retain only the <strong>LINESTRING</strong> and <strong>MULTILINESTRING</strong> geometries. These geometries represent roads as lines and multi-segmented lines, which are essential for spatial analysis in road networks.</li>
</ul></li>
<li><p><strong>Cast to LINESTRING</strong>:</p>
<ul>
<li><p>The second part of the code converts or “casts” any <strong>MULTILINESTRING</strong> geometries into <strong>LINESTRING</strong> geometries using <code>st_cast()</code>. This ensures consistency, as most road network analysis requires uniform geometry types.</p></li>
<li><p>The argument <code>group_or_split = TRUE</code> ensures that complex MULTILINESTRING geometries are split into individual LINESTRING components where necessary.</p></li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>roads_in_bangkok <span class="ot">&lt;-</span> bangkok_roads <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">st_geometry_type</span>(bangkok_roads) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"LINESTRING"</span>, <span class="st">"MULTILINESTRING"</span>))</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>roads_in_bangkok <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(roads_in_bangkok, <span class="st">"LINESTRING"</span>, <span class="at">group_or_split =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dividing-and-sampling-road-networks-lixelization-and-center-extraction-for-spatial-analysis" class="level2">
<h2 class="anchored" data-anchor-id="dividing-and-sampling-road-networks-lixelization-and-center-extraction-for-spatial-analysis">5.4 Dividing and Sampling Road Networks: Lixelization and Center Extraction for Spatial Analysis</h2>
<p>This code is part of preparing the <strong>road network data</strong> for spatial analysis by dividing the road network into <strong>lixels</strong> (linear pixels) and extracting their central points. Lixels are a crucial concept in network-based spatial analysis, particularly for road networks.</p>
<ol type="1">
<li><p><strong>Create Lixels</strong>:</p>
<ul>
<li><p><code>lixelize_lines()</code> divides the road network (<code>roads_in_bangkok</code>) into segments called <strong>lixels</strong>.</p></li>
<li><p>The argument <code>10000</code> specifies the desired length of each lixel in meters.</p></li>
<li><p>The argument <code>mindist = 5000</code> ensures a minimum distance of 5000 meters between the lixels to avoid overlap and maintain spatial resolution.</p></li>
</ul></li>
<li><p><strong>Extract Lixel Centers</strong>:</p>
<ul>
<li><code>lines_center()</code> extracts the <strong>central points</strong> of the lixels created in the previous step, storing them in <code>samples_bangkok</code>. These central points are often used as <strong>sample points</strong> for further spatial analyses, such as KDE or spatial interpolation, in road network studies.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lixels_bangkok <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(roads_in_bangkok, <span class="dv">10000</span>, <span class="at">mindist =</span> <span class="dv">5000</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>samples_bangkok <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels_bangkok)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="network-kernel-density-estimation-nkde-for-road-accident-analysis-with-parallel-processing" class="level2">
<h2 class="anchored" data-anchor-id="network-kernel-density-estimation-nkde-for-road-accident-analysis-with-parallel-processing">5.5 Network Kernel Density Estimation (NKDE) for Road Accident Analysis with Parallel Processing</h2>
<p>This code performs <strong>Network Kernel Density Estimation (NKDE)</strong> on the road network using <strong>parallel processing</strong> for faster computation. NKDE is used to estimate the density of events (e.g., accidents) over a road network, considering the underlying spatial structure of the network.</p>
<section id="key-steps-3" class="level4">
<h4 class="anchored" data-anchor-id="key-steps-3">Key Steps:</h4>
<ol type="1">
<li><p><strong>Parallel Processing Setup</strong>:</p>
<ul>
<li><code>plan(multisession)</code> enables <strong>parallel computation</strong> using multiple CPU cores, which speeds up the NKDE process by distributing tasks across different processing units.</li>
</ul></li>
<li><p><strong>NKDE Calculation</strong> (<code>nkde()</code>):</p>
<ul>
<li><p><strong>lines = lixels_bangkok</strong>: The road network (lixels) where the events (accidents) occur.</p></li>
<li><p><strong>events = bangkok_acc_data</strong>: The event data, in this case, road accidents in Bangkok.</p></li>
<li><p><strong>w = rep(1, nrow(bangkok_acc_data))</strong>: Assigns equal weight to each accident.</p></li>
<li><p><strong>samples = samples_bangkok</strong>: Central points from the lixels used as sampling locations for estimating density.</p></li>
<li><p><strong>kernel_name = “quartic”</strong>: The quartic kernel is used for smoothing the density estimation.</p></li>
<li><p><strong>bw = 1000</strong>: Bandwidth (in meters), which controls the smoothing scale of the kernel density estimation.</p></li>
<li><p><strong>method = “simple”</strong>: A simplified method for NKDE, suitable for this analysis.</p></li>
<li><p><strong>grid_shape = c(100, 100)</strong>: Specifies the grid resolution for the density estimation.</p></li>
<li><p><strong>verbose = TRUE</strong>: Enables detailed output during computation to track progress.</p></li>
</ul></li>
<li><p><strong>Future Processing</strong>:</p>
<ul>
<li><code>future()</code> is used to parallelize the NKDE computation. The result is stored in <code>future_nkde_result</code>, allowing the process to run in the background and use multiple cores efficiently.</li>
</ul></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(multisession)  <span class="co"># Parallelize using multiple CPU cores</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>future_nkde_result <span class="ot">&lt;-</span> <span class="fu">future</span>({</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">nkde</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">lines =</span> lixels_bangkok,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">events =</span> bangkok_acc_data,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(bangkok_acc_data)),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">samples =</span> samples_bangkok,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">bw =</span> <span class="dv">1000</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">div =</span> <span class="st">"bw"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>),</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">verbose =</span> <span class="cn">TRUE</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(future_nkde_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>MultisessionFuture:
Label: '&lt;none&gt;'
Expression:
{
    nkde(lines = lixels_bangkok, events = bangkok_acc_data, w = rep(1, 
        nrow(bangkok_acc_data)), samples = samples_bangkok, kernel_name = "quartic", 
        bw = 1000, div = "bw", method = "simple", grid_shape = c(100, 
            100), verbose = TRUE)
}
Lazy evaluation: FALSE
Asynchronous evaluation: TRUE
Local evaluation: TRUE
Environment: R_GlobalEnv
Capture standard output: TRUE
Capture condition classes: 'condition' (excluding 'nothing')
Globals: 3 objects totaling 205.19 MiB (sf 'lixels_bangkok' of 109.38 MiB, sf 'bangkok_acc_data' of 5.54 MiB, sf 'samples_bangkok' of 90.27 MiB)
Packages: 1 packages ('spNetwork')
L'Ecuyer-CMRG RNG seed: &lt;none&gt; (seed = FALSE)
Resolved: FALSE
Value: &lt;not collected&gt;
Conditions captured: &lt;none&gt;
Early signaling: FALSE
Owner process: df53c1dd-823d-a8bd-aeb5-9a0b3dd9086b
Class: 'MultisessionFuture', 'ClusterFuture', 'MultiprocessFuture', 'Future', 'environment'</code></pre>
</div>
</div>
<p>The <code>MultisessionFuture</code> object output indicates that the <strong>Network Kernel Density Estimation (NKDE)</strong> task has been initiated and is running asynchronously across multiple CPU cores. Here’s what the details tell us:</p>
</section>
<section id="key-details" class="level4">
<h4 class="anchored" data-anchor-id="key-details">Key Details:</h4>
<ol type="1">
<li><p><strong>Asynchronous Evaluation (TRUE)</strong>:</p>
<ul>
<li>The task is running asynchronously, meaning it is being executed in the background, which allows other processes to run concurrently. The evaluation of the NKDE will be completed independently.</li>
</ul></li>
<li><p><strong>Lazy Evaluation (FALSE)</strong>:</p>
<ul>
<li>This indicates that the task has started executing immediately, without waiting for explicit evaluation to be triggered.</li>
</ul></li>
<li><p><strong>Resources Used</strong>:</p>
<ul>
<li><p><strong>Memory Usage</strong>: The task involves significant data objects, consuming <strong>205.19 MiB</strong> of memory in total.</p>
<ul>
<li><p>The <code>lixels_bangkok</code> object, which represents the road network segments (lixels), is the largest, using about <strong>109.38 MiB</strong>.</p></li>
<li><p>The <code>samples_bangkok</code> object, which contains the sample points (centers of lixels), uses about <strong>90.27 MiB</strong>.</p></li>
<li><p>The <code>bangkok_acc_data</code> object, which stores the accident event data, takes <strong>5.54 MiB</strong>.</p></li>
</ul></li>
</ul></li>
<li><p><strong>Parallel Processing</strong>:</p>
<ul>
<li>The job is leveraging the <strong><code>spNetwork</code></strong> package to perform the network-based KDE, which is running across multiple sessions (using multicore processing). This significantly improves the computational efficiency, especially for large spatial datasets.</li>
</ul></li>
<li><p><strong>Resolved: FALSE</strong>:</p>
<ul>
<li>The NKDE task has not yet completed, meaning the density estimation process is still in progress. Once resolved, the result will be stored in <code>future_nkde_result</code> and can be accessed or plotted.</li>
</ul></li>
<li><p><strong>Tracking Output</strong>:</p>
<ul>
<li>The setup ensures that any output or conditions (e.g., errors or warnings) will be captured during the NKDE process. This is helpful for debugging and monitoring the execution status.</li>
</ul></li>
</ol>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion:</h3>
<p>The NKDE computation is actively running in parallel across multiple CPU cores to estimate the density of road accidents over the road network. The use of asynchronous evaluation allows for efficient resource utilization. Given the memory consumption, this approach is well-suited for handling large spatial datasets like road networks and accident data in Bangkok. You can monitor the status, and once completed, visualize the NKDE results to analyze accident density patterns across the road network.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>